server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: default

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets: ['localhost']
        labels:
          job: nginx
          __path__: /docker/nginx/logs/*.log


  - job_name: pihole
    static_configs:
      - targets: ['localhost']
        labels:
          job: pihole
          __path__: /docker/pihole/logs/*.log


  - job_name: mysql
    static_configs:
      - targets: ['localhost']
        labels:
          job: mysql
          __path__: /docker/mysql/logs/*.log

  - job_name: postgresql
    static_configs:
      - targets: ['localhost']
        labels:
          job: postgresql
          __path__: /docker/postgresql/logs/*.log
